name: flutter_country_picker
description: A new flutter plugin project.
version: 1.0.0
author: Alessandro Biessek <alessandrobiessek@gmail.com>
homepage: https://github.com/biessek/flutter_country_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.3

flutter:
  plugin:
    androidPackage: rocks.biessek.fluttercountrypicker
    pluginClass: FlutterCountryPickerPlugin
  assets:
    - assets/flags/
