name: flutter_country_picker
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: rocks.biessek.fluttercountrypicker
    pluginClass: FlutterCountryPickerPlugin
  assets:
   - assets/flags/