name: flutter_country_picker
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  diacritic: "^0.0.2"
flutter:
  plugin:
    androidPackage: rocks.biessek.fluttercountrypicker
    pluginClass: FlutterCountryPickerPlugin
  assets:
   - assets/flags/